# Generated by Django 5.0.6 on 2024-07-07 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MafiaRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('مافیا', 'Mafia'), ('شهورند', 'Citizen'), ('دکتر', 'Doctor'), ('پدرخوانده', 'Godfather'), ('حرفه ای', 'Professional'), ('کاراگاه', 'Detective'), ('جک', 'Jack')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
