# Generated by Django 5.0.6 on 2024-07-07 12:22

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MafiaRoleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Mafia'), (2, 'Citizen'), (3, 'Doctor'), (4, 'Godfather'), (5, 'Professional'), (6, 'Detective'), (7, 'Jack')], max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='MafiaRole',
        ),
    ]
