# Generated by Django 5.0.6 on 2024-07-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mafia', '0002_mafiarolemodel_delete_mafiarole'),
    ]

    operations = [
        migrations.AddField(
            model_name='mafiarolemodel',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mafiarolemodel',
            name='role',
            field=models.CharField(choices=[('mafia', 'Mafia'), ('citizen', 'Citizen')], max_length=10),
        ),
    ]
